spring:
  redis:
    host: 127.0.0.1
    port: 6379
  # For Connection
  #  lettuce:
  #    pool:
  #      max-active:
  # For Cache
  cache:
    redis:
      time-to-live: 100000 #毫秒
  # For Session
  #session:
  #  redis:
  #    cleanup-cron: